// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xK-WY24qzvpCyMSn_ZtqG3GD8ipAxqc',
    appId: '1:233910676083:web:3c914e7ebd7359448d5806',
    messagingSenderId: '233910676083',
    projectId: 'thewallcodedb-30731',
    authDomain: 'thewallcodedb-30731.firebaseapp.com',
    storageBucket: 'thewallcodedb-30731.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaAgb5VR3MPfpVk5MVB5CuS-qnnAf6SA',
    appId: '1:233910676083:android:b159b4c1a05783928d5806',
    messagingSenderId: '233910676083',
    projectId: 'thewallcodedb-30731',
    storageBucket: 'thewallcodedb-30731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QVRLK8SqsnscqTRQ-CYYbBEqQHXeT-s',
    appId: '1:233910676083:ios:325ade0c9106d1cb8d5806',
    messagingSenderId: '233910676083',
    projectId: 'thewallcodedb-30731',
    storageBucket: 'thewallcodedb-30731.appspot.com',
    iosBundleId: 'com.codedb.theWallApp',
  );
}
